import Banner from "./banner";

import Container from "@/components/shared/container";
import Navigation from "./navigation";
import ControlBar from "./controlBar";
export const metadata = {
    title: "Collection Page of the App",
    description: "Generated by create next app",
};

export default function AuctionLayout({ children }) {
 
    return (
        <div>
            <Banner />
            <Container>
              <Navigation/>
              <ControlBar/>
            </Container>
            {children}
        </div>
    );
}
