
export const metadata = {
    title: "Main Page of the App",
    description: "Generated by create next app",
};

export default function MainLayout({ children }) {

    return (
        <div className="pb-10">
            {children}
        </div>
    );
}
