import Container from "@/components/shared/container";
import HomeNav from "../home-nav";

export const metadata = {
    title: "Home Page of the App",
    description: "Generated by create next app",
};

export default function HomeLayout({ children }) {

    return (
        <div>
            <Container>
               <HomeNav/>
            </Container>
            {children}
        </div>
    );
}
